spring.application.name=Telehealth_With_AI
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:55432/telehealth}
spring.datasource.username=${DB_USERNAME:telehealth}
spring.datasource.password=${DB_PASSWORD:telehealth}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

server.port=8081